### PR TITLE
Don't throw if no rows are visible

### PR DESCRIPTION
**Pull request by maximumduncan**
I've found an interesting edge case with ux-datagrid, that is; if no row is visible within the viewport you get the exception: "Unable to render. Invalid activeRange."

This can happen relatively simply if, for example, an expanded row is itself higher than the viewport. This allows you to get into the situation in which both the rows above the expanded row and below the expanded row are not visible. It's even possible to reproduce this problem using your expandrows example (https://rawgit.com/obogo/ux-angularjs-datagrid/master/samples/app/index.html#/addons/expandRows). Simply expand the very last row, shrink the browser height so that the last row is the only one visible and scroll to the bottom.
It's much easier to reproduce in my app as my expanded rows can be very tall.

In this pull request I've removed the exception which normally gets thrown at this point and replaced it with a log message. All unit tests still pass and I haven't seen any other detrimental behaviour within my app so far.

Do you think this is an acceptable change?

### CODE REVIEW

**Comment by wesjones** [comment]
I added the following code to make sure the last row is still rendered in case it has changed.
I also change the error to a log as you suggested.
```
        result.startIndex = result.i = inst.getOffsetIndex(scroll);
        if (inst.rowsLength && result.startIndex === result.end) {
            result.startIndex = result.end - 1;
            inst.log(exports.errors.E1002);
        }
```

**Comment by maximumduncan** [comment]
Thanks for looking into this, but I'm finding that with 1.2.1 it's still throwing in the same situation.
This is because even though the exception has been changed to a log in `getStartingIndex()`, the same exception `throw` remains in `updateRowWatchers()`.

**Comment by wesjones** [comment]
hm, try 1.2.3. I think I changed the log part after the tag. Sorry.

**Comment by maximumduncan** [comment]
Thanks for your quick response but the only changes I can find for 1.2.1 -> 1.2.3 are changes to the readme and version numbering; no code changes at all. Am I missing something?

**Comment by wesjones** [comment]
It isn't doing a ```throw``` in the code now. It only does a log which is only an event that is fired and listened to if you have the logger addon. So there shouldn't be a problem.

```
if (inst.rowsLength && result.startIndex === result.end) {
     result.startIndex = result.end - 1;
     inst.log(exports.errors.E1002);
}
```

**Comment by maximumduncan** [comment]
It is still throwing on this line:
https://github.com/obogo/ux-angularjs-datagrid/blob/master/src/ux-datagrid.js#L886

As I said, you appear to have only changed one of the `throw`s to a `log` - this `throw` remains...

**Comment by wesjones** [comment]
Oh, I see what you are referring to.
It wasn't fixed because I forgot to set the index. Please update to 1.2.4 and let me know.

**Comment by maximumduncan** [comment]
I just tried to update to 1.2.4 using bower, but bower can only see up to 1.2.3.
So I pulled directly from master...

Unfortunately I'm still seeing the exception on the line below being thrown:
https://github.com/obogo/ux-angularjs-datagrid/blob/master/src/ux-datagrid.js#L886

It throws because the following are set to these values:

    inst.rowsLength === 500
    values.activeRange.min === -1
    values.activeRange.max === -1

"```Uncaught Error: Unable to render. Invalid activeRange.```"

I am still able to reproduce it in the same way: by expanding a row which has an expanded height greater than that of the viewport.

**Comment by wesjones** [comment]
I've pushed a new version. It should allow for your condition. I didn't remove the error, what I did is allow for the range to still be valid if there is one item that it can render.

Please update and let me know if it fixes your issue. It is not published as a release, I am still testing it's possible affects.

**Comment by maximumduncan** [comment]
Hi @wesjones, thanks for continuing to look into this.
Unfortunately your latest update (pulled from master) exhibits the same behaviour; I still get "Uncaught Error: Unable to render. Invalid activeRange." thrown on line 1835.

The variables remain:
```
inst.rowsLength === 500
values.activeRange.min === -1
values.activeRange.max === -1
```
and so the exception is thrown.

The reason that your fix doesn't help my situation is because `updateMinMax` isn't always called. In this case `updateRowWatchers()` enters with both `min` and `max` being set to `-1`. The `while (loop.i < inst.rowsLength) {` loop is entered, but the conditional: `if (offset >= loop.visibleScrollStart && offset <= loop.visibleScrollEnd) {` can return false. Thus the block of code which would call `updateMinMax()` is not executed.

It seems that that conditional fails because `offset` is storing a large number, outside of `loop.visibleScrollStart` and `loop.visibleScrollEnd`:

```
offset == 8830
loop == {
  end: 500
  i: 1
  inc: 1
  startIndex: 0
  started: 0
  visibleScrollEnd: 1323
  visibleScrollStart: 200
}
```

I get this situation by expanding the first row in the list and scrolling down a little. This first row has an expanded height of 8557 pixels.

**Comment by wesjones** [comment]
Thank you for your detailed explanation. I have not been able to duplicate this issue and would like you to edit this following example.

Here is an example of the expandRow addon.
http://obogo.github.io/ux-angularjs-datagrid/#/expandableRow

I have tried changing the style of the .expandDefault class height to 300px (since the viewport is 150px). I am not currently getting the error you speak of. I'm wondering if you could help me duplicate this in this environment so I can debug through it as well.

To edit it if using chrome in the debugger do a "cmd + o" or similar to search for file name and then type expandableRow. It will show you the css file related to the expandableRow example (it will be named ex.css like all of the rest). Open that css file, change the height at the bottom from 50px to 300px and then save (cmd + s). Then toggle the expanding row and it will open 300px tall, but no error happening.

If that doesn't work. Please contact me via my github profile and we can do a hangout or skype call so we can get to the bottom of this one.

**Comment by maximumduncan** [comment]
Hi @wesjones,

I managed to reproduce it on that demo link you supplied by setting .expandDefault to 300px and simply scrolling to the bottom.

Last messages in the log are:
```
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRowCompile
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRenderProgress
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRowCompile
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRenderProgress
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRowCompile
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRenderProgress
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRowCompile
ux-datagrid-gridLogger.js:74 events[057]::$emit datagrid:onRenderProgress
angular-ux-datagrid.js:1835 Uncaught Error: Unable to render. Invalid activeRange.
```

**Comment by wesjones** [comment]
Can you contact me on hangouts? cybus10 on gmail. Let's do a screen share
and see if we can figure out what I am missing.

**Comment by wesjones** [comment]
Ok, I think I have it working. Please update with the latest. If this works I will publish a release. 

I made an allowance that if there is one row to render even though there isn't enough viewport to see the whole row, it will render at least one. This way still maintaining the error in case something else goes wrong to notify the developer.

**Comment by maximumduncan** [comment]
And I was just about to hangouts you! I'll update and report back :)

**Comment by maximumduncan** [comment]
Good news - it works now; no errors :+1:

**Comment by wesjones** [comment]
Awesome! Release 1.2.6 has been published. Thanks for your help in nailing that one down!

**Pull request closed without merging**
